---
- hosts: all
  tasks:
  - name: Copy os release file
    copy:
      src: ../../etc/os-release-centos
      dest: /etc/os-release
      owner: root
      group: root
      mode: 0644
  - name: Copy cockpit branding directory
    copy:
      src: ../../usr/share/cockpit/branding/sotolito/
      dest: /usr/share/cockpit/branding/sotolito
      owner: root
      group: root
      mode: 0644

