---
- hosts: all
  tasks:
  - name: Copy os release file
    copy:
      src: ../../etc/os-release-centos
      dest: /etc/os-release
      owner: root
      group: root
      mode: 0644
  - name: Copy cockpit branding directory
    copy:
      src: ../../usr/share/cockpit/branding/sotolito/
      dest: /usr/share/cockpit/branding/sotolito
      owner: root
      group: root
      mode: 0644



  - name: "Set Network Interface {{ ansible_default_ipv4.interface }}"
    replace:
      dest: "/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}"
      regexp: "<IFACE>"
      replace: "{{ ansible_default_ipv4.interface }}"
  - name: "Set IP Address to {{ node_ip_address }}"
    replace:
      dest: "/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}"
      regexp: "<IP>"
      replace: "{{ node_ip_address }}"
  - name: "Reload network"
    service:
      name: network
      state: reloaded
      args: "{{ ansible_default_ipv4.interface }}"

