---
- hosts: nodes
  tasks:
  - name: Install galera server
    action: package name={{item}} state=installed
    with_items:
      - mariadb-server
      - mariadb-server-galera

  - name: Open galera ports
    action: firewalld port={{item}} state=enabled permanent=yes immediate=yes state=enabled
    with_items:
      - 3306/tcp
      - 4567/tcp
      - 4568/tcp
      - 4444/tcp
      - 4567/udp
    tags:
      - network

  - name: Copy galera configuration
    template:
      src: galera.cnf.j2
      dest: /etc/my.cnf.d/galera.cnf
      owner: root
      group: wheel
      mode: '0644'

  - name: Stop MariaDB services
    systemd:
      name: mariadb
      state: stopped

- hosts: 10.253.0.2
  tasks:
  - name: "Bootstrap galera cluster"
    command: "galera_new_cluster"



- hosts: nodes
  tasks:
  - name: Allow access to the Galera TCP ports
    action: seport ports={{ item }} proto=tcp setype=mysqld_port_t state=present
    with_items:
      - 4567
      - 4568
      - 4444
  - name: Allow access to the Galera UDP port
    seport:
      ports: 4567
      proto: tcp
      setype: http_port_t
      state: present
  - name: Start MariaDB services
    systemd:
      name: mariadb
      enabled: yes
      state: started

