---
- hosts: all
  tasks:
  - name: Creating swap partition
    parted:
      device: /dev/sda
      number: 1
      state: present
      part_end: 2GiB
  - name: Creating root partition
    parted:
      device: /dev/sda
      number: 2
      state: present
      part_end: 2GiB
      part_end: 30GiB
  - name: Creating var partition
    parted:
      device: /dev/sda
      number: 3
      state: present
      part_start: 30GiB
      part_end: 100%




