---
- hosts: all
  tasks:
  - name: Install dependencies LVM
    package:
      name: lvm2
      state: present
  - name: Creating swap partition
    parted:
      device: /dev/sda
      number: 1
      state: present
      #TODO check how to optimize this: part_start: 0s
      part_end: 2GiB
  - name: Creating root partition
    parted:
      device: /dev/sda
      number: 2
      state: present
      part_start: 2GiB
      part_end: 30GiB
  - name: Creating var partition
    parted:
      device: /dev/sda
      number: 3
      flags: [ lvm ]
      state: present
      part_start: 30GiB
      part_end: 100%
  - name: Create sotolito volume group on top of /dev/sda3
    lvg:
      vg: sotolito
      state: present
      pvs: /dev/sda3
      #pesize: 32
  - name: Create logical volume for var
    lvol:
      vg: sotolito
      lv: var
      state: present
      size: 100%FREE
      pvs: /dev/sda3
  - name: Make swap partition
    command: "mkswap /dev/sda1"
  - name: Activate swap partition
    command: "swapon -a"
  - name: Create a xfs filesystem for root (/dev/sda2)
    filesystem:
      fstype: xfs
      dev: /dev/sda2
  - name: Create a xfs filesystem for var (/dev/sotolito/var)
    filesystem:
      fstype: xfs
      dev: /dev/sotolito/var



